

# This file was *autogenerated* from the file plottime.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_200 = Integer(200); _sage_const_40 = Integer(40); _sage_const_0p001 = RealNumber('0.001'); _sage_const_3 = Integer(3)# plottime.sage

Lmagma = []
f = open("TimeMagmaHMF.log","r");
for line in f:
  v = line.strip().split(' ')
  N = ZZ(v[_sage_const_0 ])
  Psi = ZZ(v[_sage_const_1 ])
  tmagma = RR(v[_sage_const_2 ])
  if N > _sage_const_200 :
    Lmagma.append((N,tmagma))

Pmagma = points(Lmagma, scale="loglog", axes_labels=['level norm', 'time (seconds)'], legend_label="magma", color='red', marker='x', size=_sage_const_40 )

Lfdom = []
Loneword = []
f = open("TimeCohom.log","r");
for line in f:
  v = line.strip().strip('[]').split(',')
  N = ZZ(v[_sage_const_0 ])
  Psi = ZZ(v[_sage_const_1 ])
  tfdom = (ZZ(v[_sage_const_2 ])*_sage_const_0p001 )
  toneword = (ZZ(v[_sage_const_3 ])*_sage_const_0p001 )
  if N > _sage_const_200 :
    Lfdom.append((N,tfdom))
    Loneword.append((N,toneword))

Pfdom = points(Lfdom, legend_label="fdom", color='blue')
Poneword = points(Loneword, legend_label="oneword", color='green', marker="+", size=_sage_const_40 , frame=True)

(Pmagma + Pfdom + Poneword).save("time.png")

var('a,b')
__tmp__=var("x"); model = symbolic_expression(a+b*x).function(x)
print("magma", find_fit([[log(p[_sage_const_0 ]),log(p[_sage_const_1 ])] for p in Lmagma],model))
print("fdom", find_fit([[log(p[_sage_const_0 ]),log(p[_sage_const_1 ])] for p in Lfdom],model))
print("oneword", find_fit([[log(p[_sage_const_0 ]),log(p[_sage_const_1 ])] for p in Loneword],model))

