afuchprespath="/home/imb/rbait/files/code/packages/pari/Cohomology-of-Shimura-curves"
read(concat(afuchprespath,"/slp.gp"))
read(concat(afuchprespath,"/maputils.gp"))
read(concat(afuchprespath,"/map.gp"))
read(concat(afuchprespath,"/mapcov.gp"))
read(concat(afuchprespath,"/mappres.gp"))
read(concat(afuchprespath,"/afuchutils.gp"))
read(concat(afuchprespath,"/afuchpres.gp"))
read(concat(afuchprespath,"/afuchcov.gp"))
