/*
	This package implements side pairings associated to 
	maps/combinatorial embeddings of graphs in surfaces. It 
	also features algorithms to compute one-word and one-handle
	presentations for a map G->S. 
*/
/*
	Let p:X->S-Y be a covering for a compact orientable topological
	surface S and a discrete finite set Y. Let G(p) be the
   	automorphism group of p.
	Let i:G->S-Y->S be a combinatorial embedding with one vertex.
   	Also let
   	i':G'->G be a surjective map of graphs. Let v be a vertex of
   	G. The side pairing associated to (i o i') and v is the data of
   	a function
		s=i_*|_L(G'): L(G')->G(p)
   	coming from the surjective morphism of groupoids 
		(i o i')_*:pi1(G', i'^{-1}(v))->G(p).
	Where L(G) is a set of generating paths in pi1(G', i'^{-1}(v)).
   	 When G has one vertex
	and i' is the identity, pi1(G', i'^{-1}(v))=pi1(G, V(G)) is
	a group, freely generated by edges of G. In particular, 
	L(G) can be replaced by D(G) the set of oriented edges in G,
   	also called darts. When G'->G is a covering graph of 
	the form pi^{-1}(G) for some finite covering pi:S'->S, the map
	G'->S' is a combinatorial graph embedding that can be used
	to compute a side pairing associated to G'->S'-pi^{-1}(Y).
	It is then useful to first view G' as yielding a side pairing
	for Gamma instead of Gamma'. 

	A side pairing lets us represent elements of G(p) as
	words of edges in G. We choose to use straight line programs
	to represent words of edges in G. 

	A straight line program (slp) should be tought of as a procedure
	to take a set of edges E to a new set of edges E' that are 
	words in the edges of E. See slp.gp or TODO: cite paper.
*/

/* Builds slps for shortest paths in T from vertex 1*/
/*to each vertex. Then used to build the presentation*/
/*of the fundamental group of the underlying graph of G*/
/*associated to a spanning tree T.*/
map_liftalongT(G, T, TvG)={
	my(s1,s2, s, sinv, n, sc, v);
	[s1,s2]=G;
	s=(s2^-1)*s1;
	sinv=s^-1;
	n=#s1;
	sc=permcycles(s);
	v=#sc;
	vG=map_face_index([s1,s]);


   	my(seedlp, n_one);
	n_one=n-2*(v-1);
	
	my(slpspaths, pointersspaths);
	slpspaths=vector(v);
	pointersspaths=vector(v);
	slpspaths[1]=[-1,0];
	pointersspaths[1]=1;

	my(last, lastvindex, lastvTindex, index, k, e);
	k=2;
	for(i=2, v,
		/*
		   The shortest path from
			the first node of T to the node 
			of index i in the ordering of T.
		*/
		e=T[i-1][1];
		lastvindex=vG[e];
		lastvTindex=TvG[lastvindex];

		/*Recover index of last instruction in slp*/
		last=pointersspaths[lastvTindex];
		index=n+last;

		slpspaths[k]=[index, e];
		pointersspaths[i]=k;
		k++;
	);

	slpspaths=slpspaths[1..(k-1)];
	return([slpspaths, pointersspaths]);
}

/*Each path gi is homotopic to the unique shortest path in T between
face 1 and i in the dual graph (equivalently vertex 1 to i in G).
So that the tree made of the gis 
is isomorphic to T but avoids the hypothetic punctures at the center
of the faces of the dual graph. */
map_liftalongTspecial(G, T, TfG, {type=1})={
	my(s1,s2,s, sinv, n, sc, f);
	[s1,s2]=G;
	if(type, s=s2, s=(s2^-1)*s1);
	sinv=s^-1;
	n=#s1;
	sc=permcycles(s);
	f=#sc;
	fG=map_face_index([s1,s]);

	my(makeslpgammai, maxfacesize = 1);
	/*Encodes a face of Gdual starting at seed (inclusive) and*/
	/*went through in reversed orientation.*/
	makeslpgammai=(u-> 
		my(seed, e, k=1);
		if(u==1,
			seed=1;
		,/*else*/
			seed=T[u-1][2];
		);
		my(slpgammai);
		slpgammai=vector(#sc[fG[seed]]);
		e=seed;
		until(e==seed,
			/*Faut tenir compte des générateurs*/
			if(k==1, 
					slpgammai[k]=[0, s1[e]];
		    ,\\else
					slpgammai[k]=[k-1+n, s1[e]];
				
			);
			e=sinv[e];
			k++;
		);
		maxfacesize=max(maxfacesize, k-1);
		return(slpgammai);
	);
	my(slpsgammai);
	slpsgammai=vector(f,u, makeslpgammai(u));


   	my(n_one);
	n_one=n-2*(f-1);
	
	my(slpgis, pointersgi, approxtotlength=maxfacesize*n);
	/*straight line program to compute loopfaces paths.*/
	slpgis=vector(approxtotlength);
	/*Used to read the slp : pointersgi[fTindex]*/
	/*points to the index of the last edge of the path*/
	/*associated to fTindex in slpgis. Where fTindex is 
	 the index of a vertex f in the ordering of T.*/
	pointersgi=vector(f);
	slpgis[1]=[-1,0];
	pointersgi[1]=1;

	my(last, estart, eend, flastindex, flastTindex, k, e);
	k=2;
	for(i=2, f,
		/*
			The path associated to gi is used to join
			the first face to the face 
			of index i in the ordering of T.
		*/
		if(i==2,
			[estart, eend]=[1, T[1][1]];
			last=1;
		,/*else*/
			flastindex=fG[T[i-1][1]];
			flastTindex=TfG[flastindex];
			if(flastTindex==1,
				[estart, eend]=[1, T[i-1][1]];
			,/*else*/
				[estart, eend]=[T[flastTindex-1][2], T[i-1][1]];
			);
			/*Recover index of last instruction in slp*/
			last=pointersgi[flastTindex];
		);

		if(s[estart]==eend,
				/*Add Empty path*/
				/*TODO: transformer en ne rien faire et pas incrémenter k.*/
				slpgis[k]=[0, n+last];
				k++;
		,/*else*/
				e=s[estart];
				until(e==eend,
					/*Unique path contained in face*/
					/*going from s2dual[estart] to */
					/*s2dual^-1[eend] in clockwise */
					/*orientation.*/
					slpgis[k]=[n+last, e];
					e=s[e];
					last=k;
					k++;
				);
		);
		pointersgi[i]=k-1;
	);

	slpgis=slpgis[1..(k-1)];
	return([slpsgammai, slpgis, pointersgi]);
}

/*Assumes G is of genus > 0*/
findab(s2one,s1, seed, index)={
	my(a, ainv, ainvindex);
	a=seed; ainv=s1[a]; ainvindex=index[ainv];
	my(b, binv, binvindex);
	b=s2one[a]; binv=s1[b]; binvindex=index[binv];
	while(binvindex<ainvindex && b!=ainv,
		/*here aindex:=index[a]<bindex:=index[b]<ainvindex by definition*/
		b=s2one[b];
		binv=s1[b];
		binvindex=index[binv];
	);
	return([a,b]);
}

/*
   Performs a single cut and paste on the only cycle of s2one,
 representing the oneface reduction of the graph embedding
 [s1,s2].
*/
cut_and_paste_one(s2one, s1, seedslp, index)={
	my(n, n_one, a,b,vecalpha, vecbeta, vecgamma, vecdelta);
	n=#s1; n_one=permorder(s2one);
	e=seedslp;
	[a,b]=findab(s2one, s1, s2one[e], index);

	my(w);
	w=vector(n_one, u, e=s2one[e]; e);
	e=a;

	my(card);
	card=(index[b]-1)-index[a];
	vecalpha=vector(card, u, e=s2one[e]; e);
	e=s2one[e];
	
	card=(index[s1[a]]-1)-index[b];
	vecbeta=vector(card, u, e=s2one[e]; e);
	e=s2one[e];
	
	card=(index[s1[b]]-1)-index[s1[a]];
	vecgamma=vector(card, u, e=s2one[e]; e);
	e=s2one[e];
	
	vecdelta=vector(n_one-index[s1[b]], u, e=s2one[e]; e);
	
	
	my(slpc, slpd);
	slpd=slpconcat([vectoslp(vecalpha,n),[[0,b]], vectoslp(vecbeta,n)],n,,1);
	slpc=slpconcat([slpinvert(vectoslp(vecbeta,n),s1,n), slpinvert(vectoslp(vecgamma,n),s1,n), [[0, a]] ],n,,1);

	\\updated_w=gamma beta c d c^-1d^-1 alpha delta
	\\ a and b are used because they are not in the vecs
	\\ the side pairing then associates to a and b
	\\ the evaluation of slpc and slpd respectively
	my(updated_w, updated_s2one, updated_index);
	updated_w=concat([vecgamma, vecbeta, [a], [b], [s1[a]], [s1[b]], vecalpha, vecdelta]);
	updated_s2one=cycs_to_perm(n, [updated_w]);
	updated_index=map_indexcycle(updated_s2one, updated_w[1]);
		
	return([a,b, vecalpha, vecbeta, vecgamma, vecdelta, slpc, slpd, w, updated_w, updated_s2one, updated_index]);
}

/* 
   Used to filter 2g generators and build a relation in buildpres
   function in map.gp.
 */
buildrel_and_pointers(pointers, seed, s, s1, index, seen)={
	if(#pointers==1, return([pointers,[]]));
	my(e=seed, rel, j=1, newpointers, newindex, m=0);
	newindex=index;
	newpointers=vector(#pointers/2);
	rel=vector(#pointers);

	for(i=1, permorder(s),
		if(seen[s1[e]], 
			rel[i]=-newindex[s1[e]];
			m++;
		,/*else*/
			newpointers[j]=pointers[i];
			j++;
			newindex[e]+=-m;
			rel[i]=newindex[e];
		);
		e=s[e];
	);
	\\error("");
	return([newpointers, rel]);
}

\\ Given a map Gone -> S with one vertex
\\ 
map_surface_presentation(Gone, seedslp, {type="oneword"})={
	my(s1one, s2one,s2oneinv);
	[s1one,s2one]=Gone;
	n=#s1one;
	s2oneinv=s2one^-1;
	n_one=permorder(s2one);
	if(n_one==1, return([[],[],[]]));
	f=(n-n_one)/2+1;

	my(slp, pointers, seen, index, e, w);
	seen=vectorsmall(n);
	w=vectorsmall(n_one);
	e=seedslp;
	index=map_indexcycle(s2one,s2one[e]);
	\\Each edge e points to e(1).
	for(i=1, n_one,
		e=s2one[e];\
		if(!seen[s1one[e]], seen[e]=1);\
		w[i]=e;
	);
	e=seedslp;

	my(vecalpha, vecbeta, vecgamma, vecdelta,\
		slpalpha, slpbeta, slpgamma, slpdelta,\
	   	   	slpc,slpd);
	my(a,b, updated_w, updated_s2one, updated_index);
	if(type=="oneword",
		pointers=vectorsmall(n_one, i, i);
		slp=vector(n_one, i,\
			   	[0, w[i]]);
	,type=="onehandle",/*else if*/
		\\w_one=gamma beta c d c^-1d^-1 alpha delta
		\\ Recover updated pointers of gis before concatening
		\\ the loopfaces to slp and pointers.
		\\ In building pointers we wish to point to the 2*g
		\\ generators and the f loopfaces. As each edge
		\\ appears with its inverse in the one word, we
		\\ point only to the first of the two appearing
		\\ following the w_one.
		[a,b, vecalpha, vecbeta,vecgamma, vecdelta, slpc, slpd,
	   	w, updated_w, updated_s2one, updated_index]=\
			cut_and_paste_one(s2one,s1one,seedslp,index);

		slpalpha=vectoslp(vecalpha, n, 0);
		slpbeta=vectoslp(vecbeta, n, 0);
		slpgamma=vectoslp(vecgamma, n, 0);
		slpdelta=vectoslp(vecdelta, n, 0);

		[slp, pointers]=slpconcat(
			\\ SLPS
			[slpgamma, slpbeta, slpc, slpd], n,\
			\\ POINTERS
			[vector(#slpgamma, i,
				if(!seen[s1one[slpgamma[i][2]]], seen[slpgamma[i][2]]=1); i),\
			vector(#slpbeta, i,
				if(!seen[s1one[slpbeta[i][2]]], seen[slpbeta[i][2]]=1); i),\
			[#slpc], [#slpd]]\
		);
		
		\\ Add slpc^-1 and slpd^-1
		slp=concat([slp,\
			[[-(n+#slpgamma+#slpbeta+#slpc), -1]],\
		   	[[-(n+#slpgamma+#slpbeta+#slpc+#slpd), -1]]]);
		pointers=concat([pointers,[n+#slpgamma+#slpbeta+#slpc+#slpd+1,n+#slpgamma+#slpbeta+#slpc+#slpd+2]]);
		
		[slp, pointers]=slpconcat(
			\\ SLPS
			[slp,\
	   		slpalpha, slpdelta], n,\
			\\ POINTERS
			[pointers,
			vector(#slpalpha, i,
				if(!seen[s1one[slpalpha[i][2]]], seen[slpalpha[i][2]]=1); i),\
			vector(#slpdelta, i,
				if(!seen[s1one[slpdelta[i][2]]], seen[slpdelta[i][2]]=1); i)]\
		);
		s2one=updated_s2one;
		index=updated_index;
		\\ a and b are now c and d respectively for updated_index
		\\ This works as only their index in updated_w is used.
		seen[a]=1;
		seen[b]=1;
	);
	\\Pointers has size 4*g at this point, that is it points on
	\\2*g topological generators and their inverses. 
	\\This filters 2*g topological generators and builds
	\\the appropriate relation.
	my(rel);
	[pointers,rel]=buildrel_and_pointers(pointers, slp[1][2], s2one, s1one, index, seen);
	return([slp, pointers, rel]);
}

map_loopfaces(n, slpsgammai, slpgis, pointersgi)={
	my(f, n_one, rel);
	f=#slpsgammai;
	n_one=n-2*(f-1);
	
	rel=vector(f, i, n_one/2+i);
	\\ Makes slps of gammais into a single slp
   	my(slpgammais, pointersgammai);
	[slpgammais, pointersgammai]=slpconcat(slpsgammai, n,\
		vector(#slpsgammai, u, [#slpsgammai[u]])\
	);
	my(slp, pointers);
	\\ Add slp of gis and gammais 
	[slp, pointers]=slpconcat(
		\\ SLPS
		[slpgis, slpgammais], n,\
		\\ POINTERS
		[pointersgi, pointersgammai]\
	);

	\\ Add loopfaces, slp with generator set <gi, gammaj;i,j>
	\\ of size #pointers==2*f
	my(slp_loopfaces, pointers_loopfaces);
	slp_loopfaces=concat(\
			\\SLPS
			vector(f, u,\
			\\ u-th gammai
			[[u, f+u],\
			\\ compute gi^-1
			[-u, -1],\
			\\ (gi.gammai).(gi^-1)
			[(2*f+3*u)-2, (2*f+3*u)-1]])\
		);
	pointers_loopfaces=vector(f,u, 3*u);
	[slp,pointers]=slpcompose([n, 2*f], [slp, slp_loopfaces],\
			[pointers, pointers_loopfaces]
	);
	return([slp, pointers, rel]);
}

map_topological_presentation_fromT(G, T, TfG, type)={
	my(Gone, s1one, s2one, seed);
	[s1one, s2one, seed]=map_gluealongT(G, T);
	Gone=[s1one,s2one];
	my(slpsgammai, slpgis, pointersgi);
	[slpsgammai, slpgis, pointersgi]=\
			map_liftalongTspecial(G,T, TfG);

	my(surface_slp, surface_pointers,surface_rel,\
			loopfaces_slp, loopfaces_pointers, face_rel);
	[surface_slp, surface_pointers, surface_rel]=\
			map_surface_presentation(Gone, seed,  type);
	[loopfaces_slp, loopfaces_pointers, face_rel]=\
			map_loopfaces(#G[1], slpsgammai, slpgis, pointersgi);

	my(fullslp, pointers, rels);
	\\ Concatenate without connecting
	[fullslp, pointers]=slpconcat(\
			\\ SLPS
			[surface_slp, loopfaces_slp], #G[1],\
			\\ POINTERS
			[surface_pointers, loopfaces_pointers]);
	rel=concat(surface_rel, face_rel);
	return([fullslp, pointers, rel]);
}

\\ Recover presentation of a map G -> S
\\ associated to its dual map G^*->S
\\ of type "type"
map_topological_presentation(G, {type="oneword"})={
	my(Gdual);
	Gdual=map_dual(G);

	my(T, TfGdual);
	[T, TfGdual]=map_getT(Gdual);
	my(slp, pointers, rel);
	[slp, pointers, rel]=map_topological_presentation_fromT(Gdual, T, TfGdual, type);
	return([slp, pointers, rel, T, TfGdual]);
}

/*Assuming G^* has many vertices, returns a side pairing for the map 
  ((G^*)/T)^*->S, that is, for the
 map with underlying graph G-T in S, or also the gluing of the faces of
G along T, as described in framework.txt*/
map_quotientT(G, T, TvG)={
	my(vG);
	vG=map_vertex_index(G);

	my(s0one, s1one, s2one, seed);
	[s1one, s2one, seed]=map_gluealongT(G, T, 0);
	\\s2one now fixes edges of G in T,
	s0one=(s2one^-1)*s1one;

	my(slpspaths, pointersspaths);
	/*Slp and pointers of shortest paths*/
	[slpspaths, pointersspaths]=map_liftalongT(G, T, TvG);

	my(slpold, pointersold);
	/*Slp and pointers of old side pairing*/
	/*NON faudra assumer qu'on a déjà un side pairing pour G*/
	[slpold, pointersold]=map_surface_presentation([s1one, s0one], seed, "oneword");

	my(slp_conjs, pointers_conjs, e);
	e=seed;
	slp_conjs=concat(\
			\\SLPS
			vector(n_one, u,\
			\\ c.e
			e=s0one[e];
			[[u, f+TvG[vG[e]]],\
			\\ compute c^-1
			[-u, -1],\
			\\ (c.e).(c-1)
			[(n_one+f+3*u)-2, (n_one+f+3*u)-1]])\
		);
	pointers_conjs=vector(n_one,u, 3*u);
	my(slp, pointers);
	[slp, pointers]=slpconcat(
			\\SLPS
			[slpold, slpspaths], n,\
			\\POINTERS
			[pointersold, pointersspaths]\
		);

	/*Slp and pointers of new side pairing*/
	[slp, pointers]=slpcompose([n,(n_one+2*f)/2], [slp, slp_conjs],[pointers, pointers_conjs]);
	return([slp, pointers, s1one, s2one, seed]);
}

\\ Acts as if G is the dual of some map G' -> S. 
\\ Computes a spanning tree T in underlying graph of G, 
\\ corresponding to a spanning tree in the graph with vertices
\\ faces of G'-> S and edges those e such that e and s1(e) lie
\\ in different faces of G'-> S. Then computes a map G/T-> S
\\ such that the dual has underlying graph G'-T, a simple loop.
\\ Also computes a side pairing associated to G'-T -> S.
\\
\\ Used to reduce to one face or one vertex when G has neither.
\\ When S=Gamma\h and G comes from a fundamental domain D with
\\ many faces/vertices, edges of D are not necessarily
\\ loops in S so that to compute a presentation of Gamma
\\ we first need to reduce to one vertex/face.
\\
map_quotient_spair(G)={
	my(T, TvG);
	[T, TvG]=map_getT(G, 0);
	return(map_quotientT(G, T, TvG));
}
