fdomprespath="/home/imb/rbait/files/code/packages/pari/Cohomology-of-Shimura-curves"
read(concat(fdomprespath,"/slp.gp"))
read(concat(fdomprespath,"/maputils.gp"))
read(concat(fdomprespath,"/map.gp"))
read(concat(fdomprespath,"/fdompres.gp"))
read(concat(fdomprespath,"/tests/slptests.gp"))
read(concat(fdomprespath,"/tests/maptests.gp"))
read(concat(fdomprespath,"/tests/fdomprestests.gp"))
read(concat(fdomprespath,"/tests/fdomprescovtests.gp"))
